service: sls

custom:
  settings:
    POSTS_TABLE: postssTable

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment: ${self:custom.settings}
  iamRoleStatements:
   - Effect: "Allow"
     Action:
        - dynamodb:PutItem

     Resource:
      - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.POSTS_TABLE}"

functions:
  createPost:
    handler: handler.createUser
    events:
    - http:
        path: /post
        method: post
  getAllPosts:
    handler: handler.getAllPosts
    events:
    - http:
        path: /posts
        method: get
  getPosts:
    handler: handler.getPosts
    events:
    - http:
        path: /posts/{number}
        method: get
  getPost:
    handler: handler.getPost
    events:
    - http:
        path: /post/{id}
        method: get
  updatePost:
    handler: handler.updatePost
    events:
    - http:
        path: /post/{id}
        method: put
  deletePost:
    handler: handler.deletePost
    events:
    - http:
        path: /post/{id}
        method: delete

resources:
  Resources:
    postssTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.POSTS_TABLE}



        